version: "3"  # optional since v1.27.0
services:
  web:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env  
    environment:
      - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
      - DATABASE_PORT = ${DATABASE_PORT}
      - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
      - DATABASE_NAME = ${DATABASE_NAME}
      - DATABASE_USERNAME = ${DATABASE_USERNAME}
      - SECRET_KEY = ${SECRET_KEY}
      - ALGORITHM = ${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES = ${ACCESS_TOKEN_EXPIRE_MINUTES}


  postgress:
    image: postgres
    environment:
      - POSTGRES_PASSWORD = ${DATABASE_PASSWORD}
      - POSTGRES_DB = ${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: